# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dansa\Desktop\TC\Torrent-Client\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(767, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 90, 461, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.stop_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.stop_BTN.setGeometry(QtCore.QRect(650, 90, 81, 31))
        self.stop_BTN.setObjectName("stop_BTN")
        self.start_BTN = QtWidgets.QPushButton(self.centralwidget)
        self.start_BTN.setGeometry(QtCore.QRect(530, 90, 91, 31))
        self.start_BTN.setObjectName("start_BTN")
        self.tableWidgetForData = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetForData.setGeometry(QtCore.QRect(30, 130, 701, 331))
        self.tableWidgetForData.setObjectName("tableWidgetForData")
        self.tableWidgetForData.setColumnCount(6)
        self.tableWidgetForData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetForData.setHorizontalHeaderItem(5, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 33))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuoption = QtWidgets.QMenu(self.menubar)
        self.menuoption.setObjectName("menuoption")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuoption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.stop_BTN.setText(_translate("MainWindow", "STOP"))
        self.start_BTN.setText(_translate("MainWindow", "START"))
        item = self.tableWidgetForData.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.tableWidgetForData.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidgetForData.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Size"))
        item = self.tableWidgetForData.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status"))
        item = self.tableWidgetForData.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Download Speed"))
        item = self.tableWidgetForData.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Peers/Seeds"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuoption.setTitle(_translate("MainWindow", "Option"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
